import {
  bankingIcon,
  mediaIcon,
  shoppingCart,
  travelIcon,
  houseIcon,
  restaurantIcon,
  global,
  beautyIcon,
  foodIcon,
  legalIcon,
  energyIcon,
  eventIcon,
  constructionIcon,
  sportIcon,
  educationIcon,
} from 'assets'

const allReviews = [
  {
    id: 1,
    location: 'Lagos',
    dateAndTime: 'Jan. 24',
    image: '',
    username: 'user 1',
    // stars: '',
    reviewtext: 'user 1 review',
  },
  {
    id: 2,
    location: 'Ogun',
    dateAndTime: 'Jan. 24',
    image: '',
    username: 'user 2',
    // stars: '',
    reviewtext: 'user 2 review',
  },
  {
    id: 3,
    location: 'Enugu',
    dateAndTime: 'Jan. 24',
    image: '',
    username: 'user 3',
    // stars: '',
    reviewtext: 'user 3 review',
  },
  {
    id: 4,
    location: 'Kano',
    dateAndTime: 'Jan. 24',
    image: '',
    username: 'user 4',
    // stars: '',
    reviewtext: 'user 4 review',
  },
]

const allCategories = [
  {
    id: 1,
    icon: houseIcon,
    backgroundColor: '#EEEEEE',
    title: 'Public & Civil Services',
  },
  {
    id: 2,
    icon: restaurantIcon,
    backgroundColor: '#D4EDF8',
    title: 'Restaurants & Bars',
  },
  {
    id: 3,
    icon: bankingIcon,
    backgroundColor: '#FEF9C4',
    title: 'Banking & Finance',
  },
  {
    id: 4,
    icon: shoppingCart,
    backgroundColor: '#F2E7E3',
    title: 'Shopping & Fashion',
  },
  {
    id: 5,
    icon: travelIcon,
    backgroundColor: '#E3F2E6',
    title: 'Travel & Vacation',
  },
  {
    id: 6,
    icon: mediaIcon,
    backgroundColor: '#FAE8E8',
    title: 'Media & Publishing',
  },
  {
    id: 7,
    icon: global,
    backgroundColor: '#9FF6D3',
    title: 'E-commerce & Internet business',
  },
  {
    id: 8,
    icon: beautyIcon,
    backgroundColor: '#FFC5D5',
    title: 'Beauty & Well-being',
  },
  {
    id: 9,
    icon: foodIcon,
    backgroundColor: '#FFC999',
    title: 'Food, Beverages & Tobacco',
  },
  {
    id: 10,
    icon: legalIcon,
    backgroundColor: '#E3F2E6',
    title: 'Legal Services & Government',
  },
  {
    id: 11,
    icon: energyIcon,
    backgroundColor: '#D4EDF8',
    title: 'Energy & Utilities',
  },
  {
    id: 12,
    icon: eventIcon,
    backgroundColor: '#FFFBD6',
    title: 'Events & Entertainment',
  },
  {
    id: 13,
    icon: educationIcon,
    backgroundColor: '#EEEEEE',
    title: 'Education & Training',
  },
  {
    id: 14,
    icon: sportIcon,
    backgroundColor: '#9FF6D3',
    title: 'Sports & Gaming',
  },
  {
    id: 15,
    icon: constructionIcon,
    backgroundColor: '#EEEEEE',
    title: 'Construction & Manufacturing',
  },
]

export { allReviews, allCategories }
